name: MC Server Deployment

# Triggers the action everty time there is a code push to the release branches
on:
  push:
    branches:
      - main
      - qa
      - develop

permissions:
  id-token: write
  contents: read

# Specify what jobs to run
jobs:
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main'
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK deployment
        run: |
          export CI=true
          npm install -g aws-cdk
          npm i
          npm run build
          cdk synth
          cdk bootstrap
          cdk deploy --verbose --require-approval never
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          MEMORY_LIMIT: ${{ secrets.MEMORY_LIMIT }}
         
